use Tables
--Q1. What is the total revenue generated by male vs. female my_tables?
select gender, SUM("purchase amount (usd)") as revenue
from my_table
group by gender


--Q2. Which customer used a discount but still spent more than the average purchase amount? 
select "customer id", "purchase amount (usd)"
from my_table 
where "discount applied" = 'Yes' and "purchase amount (usd)" >= (select AVG("purchase amount (usd)") from my_table)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from my_table
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from my_table
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed my_tables spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(my_table_id) AS total_my_tables,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM my_table
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM my_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment my_tables into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with my_table_type as (
SELECT my_table_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS my_table_segment
FROM my_table)

select my_table_segment,count(*) AS "Number of my_tables" 
from my_table_type 
group by my_table_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(my_table_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(my_table_id) DESC) AS item_rank
    FROM my_table
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are my_tables who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(my_table_id) AS repeat_buyers
FROM my_table
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM my_table
GROUP BY age_group
ORDER BY total_revenue desc;
